id: 699659614928502815
name: VATUSA
active: true
description: Official Division Server
facility: ALL
name_format_type: first_last
title_type: division
roles:
  - id: 1074843942224412722
    name: Verified
    criteria:
      - conditions:
        - type: all
  - id: 1074842761926279310
    name: VATUSA Member
    criteria:
      - conditions:
          - type: in_division
            value: true
  - id: 699743085067763767
    name: Observer
    criteria:
      - conditions:
          - type: rating
            value: OBS
  - id: 699743084363251793
    name: Student 1
    criteria:
      - conditions:
          - type: rating
            value: S1
  - id: 699743084002672662
    name: Student 2
    criteria:
      - conditions:
          - type: rating
            value: S2
  - id: 699743083809734688
    name: Student 3
    criteria:
      - conditions:
          - type: rating
            value: S3
  - id: 699743083390042122
    name: Controller 1
    criteria:
      - conditions:
          - type: rating
            value: C1
  - id: 699743083017011200
    name: Controller 3
    criteria:
      - conditions:
          - type: rating
            value: C3
  - id: 918658942639435796
    name: Instructor 1 (Visitor)
    criteria:
      - conditions:
          - type: rating
            value: I1
          - type: in_division
            value: false
  - id: 699743082312368218
    name: Instructor 1
    criteria:
      - conditions:
          - type: rating
            value: I1
          - type: in_division
            value: true
  - id: 918659567460696075
    name: Instructor 3 (Visitor)
    criteria:
      - conditions:
          - type: rating
            value: I3
          - type: in_division
            value: false
  - id: 699743081767108648
    name: Instructor 3
    criteria:
      - conditions:
          - type: rating
            value: I3
          - type: in_division
            value: true
  - id: 699743081083175082
    name: Supervisor
    criteria:
      - conditions:
          - type: rating
            value: SUP
  - id: 699743080093581444
    name: Administrator
    criteria:
      - conditions:
          - type: rating
            value: ADM
  - id: 699669625029394493
    name: ATM/DATM
    criteria:
      - conditions:
          - type: role
            value: ATM
      - conditions:
          - type: role
            value: DATM
  - id: 699669672773288013
    name: TA
    criteria:
      - conditions:
          - type: role
            value: TA
  - id: 699669701235703828
    name: EC
    criteria:
      - conditions:
          - type: role
            value: EC
  - id: 699669757820928081
    name: FE
    criteria:
      - conditions:
          - type: role
            value: FE
  - id: 699669702544457749
    name: WM
    criteria:
      - conditions:
          - type: role
            value: WM
  - id: 717175193478365295
    name: VATUSA Developer
    criteria:
      - conditions:
          - type: role
            value: USWT
  - id: 1074835691533512754
    name: DICE Team
    criteria:
      - conditions:
          - type: role
            value: DICE
  - id: 1096981131129270373
    name: DCC Staff
    criteria:
      - conditions:
          - type: role
            value: DCC
  - id: 708602569961897986
    name: ACE Team
    criteria:
      - conditions:
          - type: role
            value: ACE
  - id: 850535607587045406
    name: Social Media Team
    criteria:
      - conditions:
          - type: role
            value: SMT
  - id: 699664936686846052
    name: VATUSA Staff
    criteria:
      - conditions:
          - type: division_staff
  - id: 1145593610268586004
    name: ARTCC Management
    criteria:
      - conditions:
          - type: role
            value: ATM
      - conditions:
          - type: role
            value: DATM
      - conditions:
          - type: role
            value: TA
  - id: 1145593686588149827
    name: ARTCC Staff
    criteria:
      - conditions:
          - type: role
            value: ATM
      - conditions:
          - type: role
            value: DATM
      - conditions:
          - type: role
            value: TA
      - conditions:
          - type: role
            value: EC
      - conditions:
          - type: role
            value: FE
      - conditions:
          - type: role
            value: WM
