apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discord-bot-web-shim
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bot.vatusa.net
      secretName: cloudflare-tls
  rules:
    - host: bot.vatusa.net
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: discord-bot-v3-web-shim
                port:
                  number: 9002
